name: smanga
description: Arabic Manga & Manhwa Reader
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & HTML scraping
  dio: ^5.4.3
  html: ^0.15.4

  # Image loading & caching
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0

  # Local storage
  sqflite: ^2.3.3
  path_provider: ^2.1.2
  path: ^1.9.0
  shared_preferences: ^2.2.3

  # State management
  flutter_riverpod: ^2.5.1

  # UI
  shimmer: ^3.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
